-- Salary Certificate cache - DDL hand-off for the DBA (UAT / PROD).
-- The app addresses the table unqualified, so the JDBC URL must carry
-- currentSchema=salary_certificate. Substitute <liquibase_db_user> and <app_db_user>.

CREATE SCHEMA IF NOT EXISTS salary_certificate;

-- Drop table
-- DROP TABLE salary_certificate.salary_certificate_cache;

CREATE TABLE IF NOT EXISTS salary_certificate.salary_certificate_cache (
	id         int8        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	cache_key  text        NOT NULL,
	payload    jsonb       NOT NULL,
	fetched_at timestamptz NOT NULL,
	CONSTRAINT salary_certificate_cache_pkey PRIMARY KEY (id),
	CONSTRAINT uk_salary_certificate_cache_cache_key UNIQUE (cache_key)
);

-- No reader today; expiry is evaluated in Java. Kept for a future purge job.
CREATE INDEX IF NOT EXISTS idx_salary_certificate_cache_fetched_at
	ON salary_certificate.salary_certificate_cache USING btree (fetched_at);

COMMENT ON COLUMN salary_certificate.salary_certificate_cache.id         IS 'Surrogate key for table convention only; nothing reads it';
COMMENT ON COLUMN salary_certificate.salary_certificate_cache.cache_key  IS 'Literal key, sal:<variant>:<POIType>:<POINumber>:<EmploymentSector>:<PayMonth>:<language>, variant is lite|full and PayMonth normalised to Greg yyyy-MM (empty when absent); POIType, EmploymentSector and language case-normalised';
COMMENT ON COLUMN salary_certificate.salary_certificate_cache.payload    IS 'Backend response body as returned by the outbound tier';
COMMENT ON COLUMN salary_certificate.salary_certificate_cache.fetched_at IS 'TTL is evaluated on read as fetched_at + configured ttl';

GRANT ALL PRIVILEGES ON SCHEMA salary_certificate TO <liquibase_db_user>;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA salary_certificate TO <liquibase_db_user>;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA salary_certificate TO <liquibase_db_user>;

GRANT USAGE ON SCHEMA salary_certificate TO <app_db_user>;
GRANT SELECT, INSERT, UPDATE ON salary_certificate.salary_certificate_cache TO <app_db_user>;

-- Default privileges attach to the creating role, so this must name Liquibase.
ALTER DEFAULT PRIVILEGES FOR ROLE <liquibase_db_user> IN SCHEMA salary_certificate
	GRANT SELECT, INSERT, UPDATE ON TABLES TO <app_db_user>;
