-- Freelance Validation cache - DDL hand-off for the DBA (UAT / PROD).
-- The app addresses the table unqualified, so the JDBC URL must carry
-- currentSchema=freelance_validation. Substitute <liquibase_db_user> and <app_db_user>.

CREATE SCHEMA IF NOT EXISTS freelance_validation;

-- Drop table
-- DROP TABLE freelance_validation.freelance_cache;

CREATE TABLE IF NOT EXISTS freelance_validation.freelance_cache (
	id         int8        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	cache_key  text        NOT NULL,
	payload    jsonb       NOT NULL,
	fetched_at timestamptz NOT NULL,
	CONSTRAINT freelance_cache_pkey PRIMARY KEY (id),
	CONSTRAINT uk_freelance_cache_cache_key UNIQUE (cache_key)
);

-- No reader today; expiry is evaluated in Java. Kept for a future purge job.
CREATE INDEX IF NOT EXISTS idx_freelance_cache_fetched_at
	ON freelance_validation.freelance_cache USING btree (fetched_at);

COMMENT ON COLUMN freelance_validation.freelance_cache.id         IS 'Surrogate key for table convention only; nothing reads it';
COMMENT ON COLUMN freelance_validation.freelance_cache.cache_key  IS 'Literal key, one form per endpoint: cert:<certificateNumber>, nin:<nationalId>, roles, categories:<rolesCode>, specialities:<rolesCode>:<categoryCode>; codes and identifiers case-normalised';
COMMENT ON COLUMN freelance_validation.freelance_cache.payload    IS 'Backend response body as returned by the outbound tier';
COMMENT ON COLUMN freelance_validation.freelance_cache.fetched_at IS 'TTL is evaluated on read as fetched_at + configured ttl';

GRANT ALL PRIVILEGES ON SCHEMA freelance_validation TO <liquibase_db_user>;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA freelance_validation TO <liquibase_db_user>;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA freelance_validation TO <liquibase_db_user>;

GRANT USAGE ON SCHEMA freelance_validation TO <app_db_user>;
GRANT SELECT, INSERT, UPDATE ON freelance_validation.freelance_cache TO <app_db_user>;

-- Default privileges attach to the creating role, so this must name Liquibase.
ALTER DEFAULT PRIVILEGES FOR ROLE <liquibase_db_user> IN SCHEMA freelance_validation
	GRANT SELECT, INSERT, UPDATE ON TABLES TO <app_db_user>;
