-- GOSI Individual Details cache - DDL hand-off for the DBA (UAT / PROD).
-- The app addresses the table unqualified, so the JDBC URL must carry
-- currentSchema=gosi. Substitute <liquibase_db_user> and <app_db_user>.

CREATE SCHEMA IF NOT EXISTS gosi;

-- Drop table
-- DROP TABLE gosi.employment_info_cache;

CREATE TABLE IF NOT EXISTS gosi.employment_info_cache (
	id         int8        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	cache_key  text        NOT NULL,
	payload    jsonb       NOT NULL,
	fetched_at timestamptz NOT NULL,
	CONSTRAINT employment_info_cache_pkey PRIMARY KEY (id),
	CONSTRAINT uk_employment_info_cache_cache_key UNIQUE (cache_key)
);

-- No reader today; expiry is evaluated in Java. Kept for a future purge job.
CREATE INDEX IF NOT EXISTS idx_employment_info_cache_fetched_at
	ON gosi.employment_info_cache USING btree (fetched_at);

COMMENT ON COLUMN gosi.employment_info_cache.id         IS 'Surrogate key for table convention only; nothing reads it';
COMMENT ON COLUMN gosi.employment_info_cache.cache_key  IS 'Literal key, person:<POINumber>:<language>, POINumber is the 10-digit NIN/Iqama and language case-normalised';
COMMENT ON COLUMN gosi.employment_info_cache.payload    IS 'Backend response body as returned by the outbound tier';
COMMENT ON COLUMN gosi.employment_info_cache.fetched_at IS 'TTL is evaluated on read as fetched_at + configured ttl';

GRANT ALL PRIVILEGES ON SCHEMA gosi TO <liquibase_db_user>;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA gosi TO <liquibase_db_user>;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA gosi TO <liquibase_db_user>;

GRANT USAGE ON SCHEMA gosi TO <app_db_user>;
GRANT SELECT, INSERT, UPDATE ON gosi.employment_info_cache TO <app_db_user>;

-- Default privileges attach to the creating role, so this must name Liquibase.
ALTER DEFAULT PRIVILEGES FOR ROLE <liquibase_db_user> IN SCHEMA gosi
	GRANT SELECT, INSERT, UPDATE ON TABLES TO <app_db_user>;
